version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres-mytripassistant-b2b-dashboard:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=mytripassistant-b2b-dashboard
    restart: unless-stopped
