export const NEXT_PUBLIC_APP_URL = process.env.NEXT_PUBLIC_APP_URL!;
export const GOOGLE_CLIENT_ID = process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID!;
export const GOOGLE_RECAPTCHA_V3_SITE_KEY =
  process.env.NEXT_PUBLIC_GOOGLE_RECAPTCHA_V3_SITE_KEY!;
export const NEXT_PUBLIC_CRISP_WEBSITE_ID =
  process.env.NEXT_PUBLIC_CRISP_WEBSITE_ID!;
